name: Release
on:
  push:
    tags:
    - '*'
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install mingw-w64
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: make get

      - name: Build
        run: make build

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: zip
          GHR_PATH: target/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}